// Code generated by genids from ui/resource.hDO NOT EDIT

package main

const (
	// IDD_DIALOG_MAIN const uintptr
	IDD_DIALOG_MAIN = 101
	// IDI_ICON1 const uintptr
	IDI_ICON1 = 102
	// IDE_INPUT_TIME const uintptr
	IDE_INPUT_TIME = 40000
	// IDE_LOG const uintptr
	IDE_LOG = 40001
	// IDB_RUN const uintptr
	IDB_RUN = 40002
	// IDE_NORMAL_TIME const uintptr
	IDE_NORMAL_TIME = 40003
	// IDE_CHAR_WAIT_TIME const uintptr
	IDE_CHAR_WAIT_TIME = 40004
	// IDE_ENTER_TIME const uintptr
	IDE_ENTER_TIME = 40005
	// IDS_WINGUI const uintptr
	IDS_WINGUI = 40006
	// IDB_CHANGECHAR const uintptr
	IDB_CHANGECHAR = 40007
)
