// Code generated by genids from ui/resource.h DO NOT EDIT

package main

const (
	// IDD_DIALOG const uintptr
	IDD_DIALOG = 104
	// IDD_DIALOG_OK const uintptr
	IDD_DIALOG_OK = 106
	// IDI_ICON1 const uintptr
	IDI_ICON1 = 107
	// IDB_BITMAP1 const uintptr
	IDB_BITMAP1 = 110
	// IDB_BITMAP2 const uintptr
	IDB_BITMAP2 = 111
	// IDD_DIALOG_TAB1 const uintptr
	IDD_DIALOG_TAB1 = 113
	// IDD_DIALOG_RICH const uintptr
	IDD_DIALOG_RICH = 114
	// IDD_DIALOG_TREE const uintptr
	IDD_DIALOG_TREE = 115
	// IDB_OK const uintptr
	IDB_OK = 40000
	// IDB_CANCEL const uintptr
	IDB_CANCEL = 40001
	// IDC_TAB_LIST1 const uintptr
	IDC_TAB_LIST1 = 40001
	// IDC_TAB_BUTTON1 const uintptr
	IDC_TAB_BUTTON1 = 40002
	// IDE_EDIT const uintptr
	IDE_EDIT = 40002
	// IDB_NORMAL const uintptr
	IDB_NORMAL = 40003
	// IDP_BMP const uintptr
	IDP_BMP = 40004
	// IDB_CHANGEBMP const uintptr
	IDB_CHANGEBMP = 40005
	// IDB_FILEBMP const uintptr
	IDB_FILEBMP = 40006
	// IDB_HWNDBMP const uintptr
	IDB_HWNDBMP = 40007
	// IDL_LISTBOX const uintptr
	IDL_LISTBOX = 40008
	// IDC_COMBOBOX const uintptr
	IDC_COMBOBOX = 40009
	// IDB_CHECK const uintptr
	IDB_CHECK = 40010
	// IDB_RADIO1 const uintptr
	IDB_RADIO1 = 40011
	// IDB_RADIO2 const uintptr
	IDB_RADIO2 = 40012
	// IDS_SLIDER const uintptr
	IDS_SLIDER = 40013
	// IDP_PROGRESSBAR const uintptr
	IDP_PROGRESSBAR = 40014
	// IDC_TAB1 const uintptr
	IDC_TAB1 = 40015
	// IDC_TAB_BUTTON_DEL const uintptr
	IDC_TAB_BUTTON_DEL = 40016
	// IDC_TAB_LABEL_COUNT const uintptr
	IDC_TAB_LABEL_COUNT = 40017
	// IDC_SPIN_EDIT const uintptr
	IDC_SPIN_EDIT = 40018
	// IDC_SPIN1 const uintptr
	IDC_SPIN1 = 40019
	// IDC_SPIN_LABEL const uintptr
	IDC_SPIN_LABEL = 40020
	// IDC_SPIN_SET42 const uintptr
	IDC_SPIN_SET42 = 40021
	// IDC_SPIN_RANGE const uintptr
	IDC_SPIN_RANGE = 40022
	// IDC_RICHEDIT1 const uintptr
	IDC_RICHEDIT1 = 40023
	// IDC_RICH_APPEND const uintptr
	IDC_RICH_APPEND = 40024
	// IDC_RICH_CLEAR const uintptr
	IDC_RICH_CLEAR = 40025
	// IDC_RICH_LABEL_LEN const uintptr
	IDC_RICH_LABEL_LEN = 40026
	// IDC_TREE1 const uintptr
	IDC_TREE1 = 40027
	// IDC_TREE_ADD_CHILD const uintptr
	IDC_TREE_ADD_CHILD = 40028
	// IDC_TREE_ADD_SIB const uintptr
	IDC_TREE_ADD_SIB = 40029
	// IDC_TREE_DELETE const uintptr
	IDC_TREE_DELETE = 40030
	// IDC_TREE_EXPAND const uintptr
	IDC_TREE_EXPAND = 40031
	// IDC_TREE_COLLAPSE const uintptr
	IDC_TREE_COLLAPSE = 40032
	// IDC_TREE_LABEL const uintptr
	IDC_TREE_LABEL = 40033
)
