// Code generated by genids from ui/resource.hDO NOT EDIT

package main

const (
	// IDD_DIALOG const uintptr
	IDD_DIALOG = 104
	// IDD_DIALOG_OK const uintptr
	IDD_DIALOG_OK = 106
	// IDI_ICON1 const uintptr
	IDI_ICON1 = 107
	// IDB_BITMAP1 const uintptr
	IDB_BITMAP1 = 110
	// IDB_BITMAP2 const uintptr
	IDB_BITMAP2 = 111
	// IDB_OK const uintptr
	IDB_OK = 40000
	// IDB_CANCEL const uintptr
	IDB_CANCEL = 40001
	// IDE_EDIT const uintptr
	IDE_EDIT = 40002
	// IDB_NORMAL const uintptr
	IDB_NORMAL = 40003
	// IDP_BMP const uintptr
	IDP_BMP = 40004
)
