// Code generated by genids from ui/resource.hDO NOT EDIT

package main

const (
	// IDD_DIALOG const uintptr
	IDD_DIALOG = 104
	// IDD_DIALOG_OK const uintptr
	IDD_DIALOG_OK = 106
	// IDI_ICON1 const uintptr
	IDI_ICON1 = 107
	// IDB_BITMAP1 const uintptr
	IDB_BITMAP1 = 110
	// IDB_BITMAP2 const uintptr
	IDB_BITMAP2 = 111
	// IDD_DIALOG_TAB1 const uintptr
	IDD_DIALOG_TAB1 = 113
	// IDB_OK const uintptr
	IDB_OK = 40000
	// IDB_CANCEL const uintptr
	IDB_CANCEL = 40001
	// IDC_TAB_LIST1 const uintptr
	IDC_TAB_LIST1 = 40001
	// IDC_TAB_BUTTON1 const uintptr
	IDC_TAB_BUTTON1 = 40002
	// IDE_EDIT const uintptr
	IDE_EDIT = 40002
	// IDB_NORMAL const uintptr
	IDB_NORMAL = 40003
	// IDP_BMP const uintptr
	IDP_BMP = 40004
	// IDB_CHANGEBMP const uintptr
	IDB_CHANGEBMP = 40005
	// IDB_FILEBMP const uintptr
	IDB_FILEBMP = 40006
	// IDB_HWNDBMP const uintptr
	IDB_HWNDBMP = 40007
	// IDL_LISTBOX const uintptr
	IDL_LISTBOX = 40008
	// IDC_COMBOBOX const uintptr
	IDC_COMBOBOX = 40009
	// IDB_CHECK const uintptr
	IDB_CHECK = 40010
	// IDB_RADIO1 const uintptr
	IDB_RADIO1 = 40011
	// IDB_RADIO2 const uintptr
	IDB_RADIO2 = 40012
	// IDS_SLIDER const uintptr
	IDS_SLIDER = 40013
	// IDP_PROGRESSBAR const uintptr
	IDP_PROGRESSBAR = 40014
	// IDC_TAB1 const uintptr
	IDC_TAB1 = 40015
)
